const Constants = {
    BTN_ACTION_MODE_URL: 0,
    BTN_ACTION_MODE_VIDEO: 1,
    BTN_ACTION_MODE_AUDIO: 2,
    BTN_ACTION_MODE_ANIMATION: 3,
    BTN_ACTION_MODE_PHONE: 4,
    BTN_ACTION_MODE_EMAIL: 5,
    BTN_ACTION_MODE_CALENDAR: 6,
    BTN_ACTION_MODE_SHOW_HIDE: 7,
    BTN_ACTION_MODE_VCARD: 8,

    INPUT_TYPE_BUTTON: 100,
    INPUT_TYPE_TOGGLE: 101,
    INPUT_TYPE_SOCIAL: 102,
};

